# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --track-allocation=user -e 'Pkg.clone(pwd()); Pkg.build("DarkSky"); Pkg.test("DarkSky"; coverage=true)'
  - julia -e 'cd(Pkg.dir("DarkSky")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
